# Site settings
title: "&lt;open tag> &lt;/close tag>"
email: oluoluoxenfree@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: oluoluoxenfree
github_username:  oluoluoxenfree

# Build settings
markdown: kramdown

#social icons

social-icons:
 - title: GitHub
   url: https://github.com/oluoluoxenfree
   class: github
 - title: LinkedIn
   url: https://uk.linkedin.com/in/oluniyiawosusi
   class: linkedin
 - title: Twitter
   url: https://twitter.com/oluoluoxenfree
   class: twitter
